### ISSUE TITLE
Hi, when will you release the mesh(OBJ+UV)?

### ISSUE THREAD

**Issue by ForrestPi** [zyj-2000/THQA-3D#1]
Hi, when will you release the mesh(OBJ+UV)?

**Comment by zyj-2000** [comment]
Thank you for your attention. We will finish organizing and posting the relevant mesh (OBJ+UV) by September.

**Comment by zyj-2000** [comment]
We have updated the README file and release all the OBJ+UV by Baidu YunPan and HuggingFace, enjoy yourself!
